// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CEE8jP9yeJM1gLGhRaA4yuBZlWQNo4g',
    appId: '1:42040448948:android:5897ef03ab7c37cecd04e1',
    messagingSenderId: '42040448948',
    projectId: 'agritechx-a1165',
    storageBucket: 'agritechx-a1165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4uejPtWqGBUkqhqZ0e90hl8_DgWtM-JA',
    appId: '1:42040448948:ios:9a002ae0fc6620e5cd04e1',
    messagingSenderId: '42040448948',
    projectId: 'agritechx-a1165',
    storageBucket: 'agritechx-a1165.firebasestorage.app',
    iosBundleId: 'com.example.agri',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamwB0iJTqXIy5poViiRIuz8q6FFYUoiM',
    appId: '1:42040448948:web:682ffd6830a9ce36cd04e1',
    messagingSenderId: '42040448948',
    projectId: 'agritechx-a1165',
    authDomain: 'agritechx-a1165.firebaseapp.com',
    storageBucket: 'agritechx-a1165.firebasestorage.app',
    measurementId: 'G-V1TVQL06D4',
  );

}